### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by EscBarr** [ByronLeeeee/Ollama-For-AMD-Installer#1]
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "ollama_installer.py", line 193, in download_and_replace_rocblas
  File "ollama_installer.py", line 166, in download_file
  File "ollama_installer.py", line 175, in update_speed
  When trying to update ROCm Libraries

**Comment by ByronLeeeee** [comment]
> Traceback (most recent call last): File "tkinter__init__.py", line 1921, in **call** File "ollama_installer.py", line 193, in download_and_replace_rocblas File "ollama_installer.py", line 166, in download_file File "ollama_installer.py", line 175, in update_speed When trying to update ROCm Libraries


Thanks for your feedback. 

Please try the lastest release [v1.1](https://github.com/ByronLeeeee/Ollama-For-AMD-Installer/releases/download/Releases/Ollama-For-AMD-Installer.exe).
